name = "BandedMats"
uuid = "1effaa55-788a-4a47-91fb-d4bdff55c3e7"
authors = ["Dongdong Kong <kongdd@users.noreply.github.com>"]
version = "0.1.2"

[deps]
UnPack = "3a884ed6-31ef-47d7-9d2a-63182c4928ed"

[compat]
UnPack = "1.0"
julia = "1.9"

[targets]
test = ["Test", "LinearAlgebra", "SparseArrays"]

[weakdeps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
